POST http://localhost:4000/refresh-token
Cookie: refresh=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE1MjViMjM2LTNmMzctNDk5MC05ZDExLTlhYjYxODEzNzcwZSIsInRva2VuVmVyc2lvbiI6MCwiaWF0IjoxNTg4NzY2MjIxLCJleHAiOjE1ODg3NjY0MDF9.Sv64TN3ICKmWPn_XZdbfSuLkOhUYroCxb85z06VJ6rE